### ISSUE TITLE
h3 is bigger than h2

### ISSUE THREAD

**Issue by mattvenn** [TinyTapeout/tinytapeout_www#107]
make h3 smaller than h2.

**Comment by urish** [comment]
The original sizes of H1/H2 (coming from the hugo theme we're using) are:
```css
h1 {
  font-size: 3.25rem; 
}

h2 {
  font-size: 2.5rem;
  line-height: 110% !important;
  margin: 2.5rem 0 1.5rem 0;
}
```

However, we have our own tinytapeout-theme.css file that overrides them to be smaller:

```css
h1 {
  font-size: 1.5em;
}

h2 {
  font-size: 1.3em;
}
```

**This is what things look like right now (with our theme overrides):**

![image](https://github.com/user-attachments/assets/3a01e57b-bb85-421f-bba2-82b0c3ea8965)


**This is what they'd look like if we removed the override, and used the default sizes:**

![image](https://github.com/user-attachments/assets/b9e1a1a4-c0c4-4fa8-8e6d-6c6433dfb62f)

**Should I remove our overrides ?**
